In [1]:
import numpy as np

In [2]:
alist = [1, 2, 3, 4, 5]
narray = np.array([1, 2, 3, 4])

In [3]:
print(alist)
print(narray)

print(type(alist))
print(type(narray))

[1, 2, 3, 4, 5]
[1 2 3 4]
<class 'list'>
<class 'numpy.ndarray'>


In [4]:
print(narray + narray)
print(alist + alist)

[2 4 6 8]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [5]:
print(narray * 3)
print(alist * 3)

[ 3  6  9 12]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [6]:
npmatrix1 = np.array([narray, narray, narray])
npmatrix2 = np.array([alist, alist, alist])
npmatrix3 = np.array([narray, [1, 1, 1, 1], narray])

print(npmatrix1)
print(npmatrix2)
print(npmatrix3)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
[[1 2 3 4]
 [1 1 1 1]
 [1 2 3 4]]


In [7]:
okmatrix = np.array([[1, 2], [3, 4]])
print(okmatrix)
print(okmatrix * 2)

[[1 2]
 [3 4]]
[[2 4]
 [6 8]]


In [8]:
badmatrix = np.array([[1, 2], [3, 4], [5, 6, 7]])
print(badmatrix)
print(badmatrix * 2)

[list([1, 2]) list([3, 4]) list([5, 6, 7])]
[list([1, 2, 1, 2]) list([3, 4, 3, 4]) list([5, 6, 7, 5, 6, 7])]


In [9]:
result = okmatrix * 2 + 1
print(result)

[[3 5]
 [7 9]]


In [10]:
result1 = okmatrix + okmatrix
print(result1)

[[2 4]
 [6 8]]


In [11]:
result2 = okmatrix - okmatrix
print(result2)

[[0 0]
 [0 0]]


In [13]:
print(okmatrix * okmatrix)

[[ 1  4]
 [ 9 16]]


In [14]:
matrix3x2 = np.array([[1, 2], [3, 4], [5, 6]]) # Define a 3x2 matrix
print('Original matrix 3 x 2')
print(matrix3x2)
print('Transposed matrix 2 x 3')
print(matrix3x2.T)

Original matrix 3 x 2
[[1 2]
 [3 4]
 [5 6]]
Transposed matrix 2 x 3
[[1 3 5]
 [2 4 6]]


In [15]:
nparray = np.array([1, 2, 3, 4])
print(nparray)
print(nparray.T)

[1 2 3 4]
[1 2 3 4]


In [16]:
nparray = np.array([[1, 2, 3, 4]])
print(nparray)
print(nparray.T)

[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]


In [17]:
nparray1 = np.array([1, 2, 3, 4])
norm1 = np.linalg.norm(nparray1)

nparray2 = np.array([[1, 2], [3, 4]])
norm2 = np.linalg.norm(nparray2)

print(norm1)
print(norm2)

5.477225575051661
5.477225575051661


In [18]:
# axis=0 means norm of each column, axis=1 meant norm of each row
nparray2 = np.array([[1,1], [2,2], [3,3]])

normByCols = np.linalg.norm(nparray2, axis=0)
normByRows = np.linalg.norm(nparray2, axis=1)

print(normByCols)
print(normByRows)

[3.74165739 3.74165739]
[1.41421356 2.82842712 4.24264069]


In [19]:
# Dot product
nparray1 = np.array([0, 1, 2, 3])
nparray2 = np.array([4, 5, 6, 7])

flavor1 = np.dot(nparray1, nparray2) # accepts arrays and lists without problems
print(flavor1)

flavor2 = np.sum(nparray1 * nparray2)
print(flavor2)

flavor3 = nparray1 @ nparray2
print(flavor3)

flavor4 = 0
for a, b in zip(nparray1, nparray2):
    flavor4 += a * b

print(flavor4)

# norm is square root of the dot product of the vector with itself, so we can do sqrt(a•a)

38
38
38
38


In [21]:
# sums, means by rows or columns
# axis=0 means sum the elements of each column
# axis=1 means sum elements of each row together

nparray2 = np.array([[1, -1], [2, -2], [3, -3]])
print(np.sum(nparray2, axis=0))
print(np.sum(nparray2, axis=1))
print(np.mean(nparray2, axis=0))
print(np.mean(nparray2, axis=1))

[ 6 -6]
[0 0 0]
[ 2. -2.]
[0. 0. 0.]


In [22]:
# center columns of a matrix: remove the column mean from each element within the column. Sum by columns of a centered matrix is always 0

nparray2 = np.array([[1, 1], [2, 2], [3, 3]]) # Define a 3 x 2 matrix. 

nparrayCentered = nparray2 - np.mean(nparray2, axis=0) # Remove the mean for each column

print('Original matrix')
print(nparray2)
print('Centered by columns matrix')
print(nparrayCentered)

print('New mean by column')
print(nparrayCentered.mean(axis=0))

# This process does not apply to row centering!

Original matrix
[[1 1]
 [2 2]
 [3 3]]
Centered by columns matrix
[[-1. -1.]
 [ 0.  0.]
 [ 1.  1.]]
New mean by column
[0. 0.]


In [23]:
nparray2 = np.array([[1, 3], [2, 4], [3, 5]]) # Define a 3 x 2 matrix. 

nparrayCentered = nparray2.T - np.mean(nparray2, axis=1) # Remove the mean for each row
nparrayCentered = nparrayCentered.T # Transpose back the result

print('Original matrix')
print(nparray2)
print('Centered by columns matrix')
print(nparrayCentered)

print('New mean by rows')
print(nparrayCentered.mean(axis=1))

Original matrix
[[1 3]
 [2 4]
 [3 5]]
Centered by columns matrix
[[-1.  1.]
 [-1.  1.]
 [-1.  1.]]
New mean by rows
[0. 0. 0.]


In [24]:
nparray2 = np.array([[1, 3], [2, 4], [3, 5]]) # Define a 3 x 2 matrix. 

mean1 = np.mean(nparray2) # Static way
mean2 = nparray2.mean()   # Dinamic way

print(mean1, ' == ', mean2)

3.0  ==  3.0
